# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-07-23 09:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20180717_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 23, 9, 29, 29, 262573, tzinfo=utc)),
        ),
    ]
