# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-08-06 14:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20180801_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 6, 14, 46, 29, 339807, tzinfo=utc)),
        ),
    ]
