# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-08-12 05:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20180812_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 12, 5, 57, 46, 19246, tzinfo=utc)),
        ),
    ]
